### ISSUE TITLE
Parent collapse issue

### ISSUE THREAD

**Issue by punitg862** [yogendrabagoriya/YB-MultiLevel-TableView#1]
when i expand parent it shows child but when i collapse their child it delete child with all parent below this parent ..

**Comment by yogendrabagoriya** [comment]
@punitg862 I just download and test it. Its working fine. App is showing 3 level's of tree. and If user tap on lowest level then app takes him to next screen. Tell me if you facing any issue..!!!

**Comment by punitg862** [comment]
If you tap on level2 then child creat and shoe and again tap child deleted
with parent if you don't mind and free call me i explain and with right
code..

**Comment by yogendrabagoriya** [comment]
When you tap on 3rd level, then it taking user on next screen, Its Not Deleting. It's performing transition. @punitg862

**Comment by punitg862** [comment]
But i said, 2 level (parent level) not child level

**Comment by punitg862** [comment]
Can you off multi expanding at parent level.. Open only one at a time and
last expanding collapse when another expand.. Can you do plz..

**Comment by yogendrabagoriya** [comment]
@punitg862 You correct.. got the issue. Just resolved.. Thanks
